### ISSUE TITLE
 int4 量化模型，目前启动后无法进行对话，输入对话内容无响应，控制台有错误提示

### ISSUE THREAD

**Issue by jhjade** [lewangdev/chatglm2-6b-colab#2]
![image](https://github.com/lewangdev/chatglm2-6b-colab/assets/66857797/58edeef0-c9e0-49be-a674-1e64a279a3c0)
![image](https://github.com/lewangdev/chatglm2-6b-colab/assets/66857797/245f8b5b-5d25-4bf4-b605-d03df330dc83)

**Comment by jhjade** [comment]
将 gradio==3.39.0 版本降低后正常了

**Comment by lewangdev** [comment]
感谢，已经修改了
